In [14]:
import nltk
import pandas as pd
import numpy as np
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [15]:
data = {
    'Song Name': [
        'Channa Mereya', 'Zinda', 'Love You Zindagi', 'Tum Hi Ho', 'Malang',
        'Apna Time Aayega', 'Raabta', 'Kabira', 'Ilahi', 'Tera Yaar Hoon Main'
    ],
    'Artist': [
        'Arijit Singh', 'Siddharth Mahadevan', 'Amit Trivedi', 'Arijit Singh', 'Ved Sharma',
        'Ranveer Singh', 'Arijit Singh', 'Tochi Raina', 'Arijit Singh', 'Arijit Singh'
    ],
    'Mood Description': [
        'heartbreak emotional love',
        'motivational powerful struggle',
        'happy optimistic fresh',
        'romantic emotional longing',
        'intense bold thrilling',
        'rebel powerful inspiring',
        'romantic dreamy magical',
        'emotional nostalgic thoughtful',
        'wanderlust adventure freedom',
        'friendship emotional bond'
    ]
}


df = pd.DataFrame(data)

In [ ]:
stemmer = PorterStemmer()

def preprocess(text):
    words = nltk.word_tokenize(text.lower())
    stemmed = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed)

df['Processed Mood'] = df['Mood Description'].apply(preprocess)

In [ ]:
vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(df['Processed Mood']).toarray()

[[0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [18]:
inverted_index = {}
for idx, mood in enumerate(df['Processed Mood']):
    for word in mood.split():
        if word not in inverted_index:
            inverted_index[word] = []
        inverted_index[word].append(idx)

In [ ]:
def recommend(user_input):
    user_input_processed = preprocess(user_input)
    user_vector = vectorizer.transform([user_input_processed]).toarray()
    similarities = cosine_similarity(user_vector, vectors)[0]
    top_indices = similarities.argsort()[-3:][::-1]

    print("Recommended Songs:") 
    for i in top_indices:
        print(f"{df.iloc[i]['Song Name']} by {df.iloc[i]['Artist']} (Score: {similarities[i]:.2f})")


In [29]:
user_mood = input("Enter your mood: ")
recommend(user_mood)

Recommended Songs:
Tera Yaar Hoon Main by Arijit Singh (Score: 0.58)
Kabira by Tochi Raina (Score: 0.58)
Channa Mereya by Arijit Singh (Score: 0.58)
